# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=16, verbose_name='Название игры')),
            ],
            options={
                'verbose_name': 'Созданная игра',
                'verbose_name_plural': 'Созданные игры',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сессия у игры',
                'verbose_name_plural': 'Сессии у игр',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('sub_email', models.EmailField(max_length=254, verbose_name='Доп. эл. почта')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.City', verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Персональные данные',
                'verbose_name_plural': 'Персональные данные',
            },
        ),
        migrations.CreateModel(
            name='PersonTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField(verbose_name='Роль')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя для проведенной игры')),
                ('count_team', models.IntegerField(verbose_name='Количество команд')),
                ('status', models.IntegerField(verbose_name='Статус игры')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
            },
        ),
        migrations.CreateModel(
            name='SessionTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('results', models.IntegerField(verbose_name='Результаты')),
            ],
            options={
                'verbose_name': 'Сессия у команды',
                'verbose_name_plural': 'Сессии у команд',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название команды')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Person', verbose_name='Лидер')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='landing.Game', verbose_name='ID игры')),
                ('info', models.TextField(verbose_name='Описание игры')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка к игре')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Информация об игре',
                'verbose_name_plural': 'Информация об играх',
            },
        ),
        migrations.AddField(
            model_name='personteam',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Team'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Game'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Session'),
        ),
        migrations.AddField(
            model_name='game',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
    ]
