# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=16, verbose_name='Логин')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(unique='true', verbose_name='Ключ игры')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль от игры')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Account')),
            ],
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название игры')),
                ('info', models.TextField(verbose_name='Описание игры')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка к игре')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.City')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('sub_email', models.EmailField(max_length=254, verbose_name='Доп. эл. почта')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Account')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.City')),
            ],
        ),
        migrations.CreateModel(
            name='PersonTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Resault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Счёт команды')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя для проведенной игры')),
                ('count_team', models.IntegerField(verbose_name='Количество команд')),
            ],
        ),
        migrations.CreateModel(
            name='SessionTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название команды')),
            ],
        ),
        migrations.AddField(
            model_name='resault',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Session'),
        ),
        migrations.AddField(
            model_name='resault',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Team'),
        ),
        migrations.AddField(
            model_name='personteam',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Team'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Session'),
        ),
    ]
