# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resault',
            new_name='Result',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаунт пользователя', 'verbose_name_plural': 'Аккаунты пользователей'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Созданная игра', 'verbose_name_plural': 'Созданные игры'},
        ),
        migrations.AlterModelOptions(
            name='gameinfo',
            options={'verbose_name': 'Информация об игре', 'verbose_name_plural': 'Информация об играх'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персональные данные', 'verbose_name_plural': 'Персональные данные'},
        ),
    ]
