# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170907_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='game',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='landing.Game', verbose_name='ID игры'),
        ),
    ]
