# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20170907_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='landing.Person', verbose_name='Логин'),
        ),
    ]
