# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20170907_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personteam',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='personteam',
            name='team_id',
        ),
        migrations.DeleteModel(
            name='SessionTeam',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameInfo',
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonTeam',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
