# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя для проведенной игры')),
                ('count_team', models.IntegerField(default=0, verbose_name='Количество команд')),
                ('status', models.IntegerField(verbose_name='Статус игры')),
                ('games', models.ManyToManyField(to='game.GameInfo')),
                ('teams', models.ManyToManyField(to='social.Team')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
            },
        ),
    ]
