# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('landing', '0006_auto_20170908_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('sub_email', models.EmailField(max_length=254, verbose_name='Доп. эл. почта')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Персональные данные',
                'verbose_name_plural': 'Персональные данные',
            },
        ),
    ]
