# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20170909_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.City', verbose_name='Город'),
        ),
    ]
