# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonTeam',
            new_name='Role',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль игрока в команде', 'verbose_name_plural': 'Роли игрков в командах'},
        ),
    ]
