# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20170909_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='Лидер'),
        ),
    ]
