# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20170909_2032'),
        ('social', '0004_auto_20170909_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='MemberTeam',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='social.MemberTeam', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Название команды'),
        ),
    ]
