# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20170913_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberteam',
            name='role',
            field=models.CharField(max_length=16, null=True, verbose_name='Роль'),
        ),
    ]
