# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20170913_0150'),
        ('social', '0008_auto_20170913_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberteam',
            options={'verbose_name': 'Связь между игроком и командой', 'verbose_name_plural': 'Связь между игроками и командами'},
        ),
        migrations.RemoveField(
            model_name='memberteam',
            name='lead',
        ),
        migrations.AddField(
            model_name='team',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='person.Person', verbose_name='Лидер'),
        ),
    ]
